version: '3.9'
services:
  # DuckDB (Python version)
  duckdb-python:
    build:
      context: .
      dockerfile: Dockerfile.duckdb-python
    volumes:
      - ./data:/data
    tty: true

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: pg_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: benchmark
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # MongoDB
  mongo:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
